In [47]:
import pandas as pd
import numpy as np
df = pd.read_csv("salmon_quants/salmon.Sample1.quant.sf", sep='\t')


df['NumReads'] = df['NumReads'].apply(np.floor).astype(int)
df = df.drop(columns=['Length', 'EffectiveLength', 'TPM'])
df.columns = df.iloc[0]
df = df[1:]
df.to_csv('sample1.test.txt',index=False, sep='\t')
df.head()

0  ENST00000632684.1  0
1  ENST00000434970.2  0
2  ENST00000448914.1  0
3  ENST00000415118.1  0
4  ENST00000390567.1  0
5  ENST00000439842.1  0

In [23]:
df1 = pd.read_csv("sample1.test.txt", sep='\t')

df1.head()

   ENST00000632684.1  0.0
0  ENST00000434970.2  0.0
1  ENST00000448914.1  0.0
2  ENST00000415118.1  0.0
3  ENST00000390567.1  0.0
4  ENST00000439842.1  0.0

In [8]:
df2 = pd.read_csv("htseq_counts/Sample1.txt", sep='\t')
df2.head()

   ENSG00000000003  0
0  ENSG00000000005  0
1  ENSG00000000419  0
2  ENSG00000000457  0
3  ENSG00000000460  0
4  ENSG00000000938  0

In [58]:

import pandas as pd

# sample1
df1 = pd.read_csv("salmon_quants/salmon.Sample1.quant.sf", sep='\t')
df1['NumReads'] = df1['NumReads'].apply(np.floor).astype(int)
df1 = df1.drop(columns=['Length', 'EffectiveLength', 'TPM'])
df1.columns = df1.iloc[0]
df1 = df1[1:] 
df1.to_csv('salmon_quants/Sample1.txt',index=False, sep='\t')

# sample2
df2 = pd.read_csv("salmon_quants/salmon.Sample2.quant.sf", sep='\t')
df2['NumReads'] = df2['NumReads'].apply(np.floor).astype(int)
df2 = df2.drop(columns=['Length', 'EffectiveLength', 'TPM'])
df2.columns = df2.iloc[0]
df2 = df2[1:] 
df2.to_csv('salmon_quants/Sample2.txt',index=False, sep='\t')


# sample3
df3 = pd.read_csv("salmon_quants/salmon.Sample3.quant.sf", sep='\t')
df3['NumReads'] = df3['NumReads'].apply(np.floor).astype(int)
df3 = df3.drop(columns=['Length', 'EffectiveLength', 'TPM'])
df3.columns = df3.iloc[0]
df3 = df3[1:] 
df3.to_csv('salmon_quants/Sample3.txt',index=False, sep='\t')


# sample4
df4 = pd.read_csv("salmon_quants/salmon.Sample4.quant.sf", sep='\t')
df4['NumReads'] = df4['NumReads'].apply(np.floor).astype(int)
df4 = df4.drop(columns=['Length', 'EffectiveLength', 'TPM'])
df4.columns = df4.iloc[0]
df4 = df4[1:] 
df4.to_csv('salmon_quants/Sample4.txt',index=False, sep='\t')


# sample5
df5 = pd.read_csv("salmon_quants/salmon.Sample5.quant.sf", sep='\t')
df5['NumReads'] = df5['NumReads'].apply(np.floor).astype(int)
df5 = df5.drop(columns=['Length', 'EffectiveLength', 'TPM'])
df5.columns = df5.iloc[0]
df5 = df5[1:] 
df5.to_csv('salmon_quants/Sample5.txt',index=False, sep='\t')


# sample6
df6 = pd.read_csv("salmon_quants/salmon.Sample6.quant.sf", sep='\t')
df6['NumReads'] = df6['NumReads'].apply(np.ceil).astype(int)
df6 = df6.drop(columns=['Length', 'EffectiveLength', 'TPM'])
df6.columns = df6.iloc[0]
df6 = df6[1:] 
df6.to_csv('salmon_quants/Sample6.txt',index=False, sep='\t')

# !cd RNA-SEQ-Tutorial-PART1/ && git add . && git commit -m "salmon-quants complete" && git push origin master

In [61]:
df6.loc[df6[0]>1]

0        ENST00000632684.1   0
4080     ENST00000370331.5   2
4681     ENST00000460376.5   2
4743     ENST00000552951.6   7
6789     ENST00000596217.1   3
7527     ENST00000367674.6   2
8003     ENST00000521728.5   2
9481     ENST00000319637.6   2
9578     ENST00000406053.5   3
13854    ENST00000518219.5   2
15077    ENST00000526457.3   3
19022    ENST00000389005.5   2
20010    ENST00000578049.3   2
20371    ENST00000569510.5   3
24056    ENST00000483979.1   2
26330    ENST00000379558.4   2
26531    ENST00000570717.5   2
28217    ENST00000368905.8   2
29185    ENST00000409562.7   4
37214    ENST00000558583.2   4
39866    ENST00000521647.1   2
40577    ENST00000610020.1   7
41593    ENST00000586722.5   2
45065    ENST00000481617.6   7
45297    ENST00000604604.1   3
47019    ENST00000264170.8   2
47665    ENST00000323468.9   2
48405    ENST00000571707.1   2
52767    ENST00000310613.7   4
55667    ENST00000256646.6   4
62826    ENST00000471841.5   5
...                    ...  ..
108559   ENST00000582797.5   3
112936   ENST00000497426.5   2
113926   ENST00000529945.2   3
114768   ENST00000358465.6   2
116349   ENST00000536575.5   3
119359   ENST00000480719.1   2
121272   ENST00000372977.7   2
122597   ENST00000555870.5   5
127093   ENST00000611593.1   4
127127   ENST00000483793.5   2
128130   ENST00000309733.5   6
128484  ENST00000264658.10   2
131123   ENST00000443751.3   2
138273   ENST00000370521.7   2
139480   ENST00000621309.4   2
140265   ENST00000566753.5  10
140827   ENST00000295269.4   2
141990   ENST00000264663.9   2
144472   ENST00000355520.5   3
145408   ENST00000340717.4   2
147302   ENST00000474698.5   3
152533   ENST00000639970.1   4
152534   ENST00000640719.1   3
152538   ENST00000640347.1   3
152543   ENST00000640587.1   2
152545   ENST00000640720.1   3
156364   ENST00000426371.2   2
159559   ENST00000411857.2   2
166506   ENST00000456826.2   2
169144   ENST00000619190.1   2

[89 rows x 2 columns]